name: Discord Issue Notifications

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification according to labels
        run: |
          # Use the *real* labels from GitHub event data
          LABELS_JSON="${{ toJson(github.event.issue.labels) }}"

          # Gather info about the current issue
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_URL="${{ github.event.issue.html_url }}"

          echo "Labels JSON: $LABELS_JSON"

          # Check if "frontend" label is present
          if echo "$LABELS_JSON" | grep -qi "frontend"; then
            echo "Sending to FRONTEND webhook..."
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "username": "GitHub Issues Bot",
                "embeds": [{
                  "title": "Nouvelle issue FRONTEND",
                  "description": "**Titre**: '"$ISSUE_TITLE"'\n**Lien**: '"$ISSUE_URL"'",
                  "color": 3066993
                }]
              }' \
              "${{ secrets.DISCORD_WEBHOOK_FRONTEND }}"

          # Check if "backend" label is present
          elif echo "$LABELS_JSON" | grep -qi "backend"; then
            echo "Sending to BACKEND webhook..."
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "username": "GitHub Issues Bot",
                "embeds": [{
                  "title": "Nouvelle issue BACKEND",
                  "description": "**Titre**: '"$ISSUE_TITLE"'\n**Lien**: '"$ISSUE_URL"'",
                  "color": 15105570
                }]
              }' \
              "${{ secrets.DISCORD_WEBHOOK_BACKEND }}"

          # Otherwise, send to the default Discord webhook
          else
            echo "Sending to DEFAULT webhook..."
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "username": "GitHub Issues Bot",
                "embeds": [{
                  "title": "Nouvelle issue (Autre)",
                  "description": "**Titre**: '"$ISSUE_TITLE"'\n**Lien**: '"$ISSUE_URL"'",
                  "color": 7506394
                }]
              }' \
              "${{ secrets.DISCORD_WEBHOOK }}"
