name: Discord Issue Notifications

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification according to labels
        run: |
          # Manually define LABELS_JSON with single quotes
          LABELS_JSON='[
            {
              "color": "1CA452",
              "default": false,
              "description": "For issues specific to the React frontend.",
              "id": 7881999609,
              "name": "frontend",
              "node_id": "LA_kwDONdZGMc8AAAAB1c3E-Q",
              "url": "https://api.github.com/repos/T1WiLLi/POTI/labels/frontend"
            }
          ]'

          # Gather info about the current issue
          ISSUE_TITLE="Test workflows discord 2"
          ISSUE_URL="https://github.com/T1WiLLi/POTI/issues/7"

          # Check if "frontend" label is present
          if echo "$LABELS_JSON" | grep -qi "frontend"; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "username": "GitHub Issues Bot",
                "embeds": [{
                  "title": "Nouvelle issue FRONTEND",
                  "description": "**Titre**: '"$ISSUE_TITLE"'\n**Lien**: '"$ISSUE_URL"'",
                  "color": 3066993
                }]
              }' \
              "***"   # Replace with your front-end webhook secret

          # Check if "backend" label is present
          elif echo "$LABELS_JSON" | grep -qi "backend"; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "username": "GitHub Issues Bot",
                "embeds": [{
                  "title": "Nouvelle issue BACKEND",
                  "description": "**Titre**: '"$ISSUE_TITLE"'\n**Lien**: '"$ISSUE_URL"'",
                  "color": 15105570
                }]
              }' \
              "***"   # Replace with your back-end webhook secret

          # Otherwise, send to the default Discord webhook
          else
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "username": "GitHub Issues Bot",
                "embeds": [{
                  "title": "Nouvelle issue (Autre)",
                  "description": "**Titre**: '"$ISSUE_TITLE"'\n**Lien**: '"$ISSUE_URL"'",
                  "color": 7506394
                }]
              }' \
              "***"   # Replace with your default webhook secret
