name: Discord Issue Notifications

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification according to labels
        run: |
          # Hardcode LABELS_JSON for local testing:
          # Use single quotes so internal double quotes don't break the script
          LABELS_JSON='[
            {
              "default": false,
              "description": "For issues specific to the React frontend.",
              "id": 7881999609,
              "name": "frontend",
              "node_id": "LA_kwDONdZGMc8AAAAB1c3E-Q",
              "url": "https://api.github.com/repos/T1WiLLi/POTI/labels/frontend"
            }
          ]'

          # Or use real GitHub labels from the event:
          # LABELS_JSON='${{ toJson(github.event.issue.labels) }}'

          ISSUE_TITLE="Test workflows discord 4"
          ISSUE_URL="https://github.com/T1WiLLi/POTI/issues/7"

          echo "Labels JSON: $LABELS_JSON"

          # Check if "frontend" label is present
          if echo "$LABELS_JSON" | grep -qi "frontend"; then
            echo "Sending to FRONTEND webhook..."
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "username": "GitHub Issues Bot",
                "embeds": [{
                  "title": "Nouvelle issue FRONTEND",
                  "description": "**Titre**: '"$ISSUE_TITLE"'\n**Lien**: '"$ISSUE_URL"'",
                  "color": 3066993
                }]
              }' \
              "${{ secrets.DISCORD_WEBHOOK_FRONTEND }}"

          elif echo "$LABELS_JSON" | grep -qi "backend"; then
            echo "Sending to BACKEND webhook..."
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "username": "GitHub Issues Bot",
                "embeds": [{
                  "title": "Nouvelle issue BACKEND",
                  "description": "**Titre**: '"$ISSUE_TITLE"'\n**Lien**: '"$ISSUE_URL"'",
                  "color": 15105570
                }]
              }' \
              "${{ secrets.DISCORD_WEBHOOK_BACKEND }}"

          else
            echo "Sending to DEFAULT webhook..."
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "username": "GitHub Issues Bot",
                "embeds": [{
                  "title": "Nouvelle issue (Autre)",
                  "description": "**Titre**: '"$ISSUE_TITLE"'\n**Lien**: '"$ISSUE_URL"'",
                  "color": 7506394
                }]
              }' \
              "${{ secrets.DISCORD_WEBHOOK }}"